name: Build and deploy documentation site
on:
  push:
    branches:
      - main

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v2
        with:
          # leave cache off until i figure out groups
          enable-cache: false

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Python 3.12.8
        run: uv python install 3.12.8

      - name: Install dependencies, with docs dependencies
        run: uv sync --group docs

      - name: Build site with mkdocs
        run: uv run mkdocs build -d _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy-site:
    needs: build-site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
