name: Check code with ruff
on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"
      - "pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint with Ruff using Python 3.11.10
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python 3.11.10
        run: uv python install 3.11.10

      - name: Install dependencies
        run: uv sync -p 3.11.10

      - name: Run Ruff linting
        run: uv run python -m ruff check . --output-format=full

      - name: Run Ruff formatting check
        run: uv run python -m ruff format --check .
