name: Type hinting with mypy
on:
  pull_request:
    branches:
      - main
    paths:
      - splinkclickhouse/**
      - pyproject.toml

jobs:
  mypy:
    runs-on: ubuntu-20.04
    name: Check type hinting with mypy
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python 3.9.10
        run: uv python install 3.9.10

      - name: Install dependencies
        run: uv sync -p 3.9.10

      - name: Run mypy
        run: uv run python -m mypy splinkclickhouse
